[project]
name = "comfyui-utils-nodes"
description = "Nodes:LoadImageWithSwitch, ImageBatchOneOrMore, ModifyTextGender, ImageCompositeMaskedWithSwitch, ColorCorrectOfUtils, SplitMask, MaskFastGrow, CheckpointLoaderSimpleWithSwitch, ImageResizeTo8x, MatchImageRatioToPreset etc."
version = "1.0.8"
license = "LICENSE"
dependencies = []

[project.urls]
Repository = "https://github.com/zhangp365/ComfyUI-utils-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "zhangp365"
DisplayName = "ComfyUI-utils-nodes"
Icon = ""
