[project]
name = "comfyui-utils-nodes"
description = "Nodes:LoadImageWithSwitch, ImageBatchOneOrMore, ModifyTextGender, GenderControlOutput, ImageCompositeMaskedWithSwitch, ColorCorrectOfUtils, SplitMask, MaskFastGrow, CheckpointLoaderSimpleWithSwitch, ImageResizeTo8x, MatchImageRatioToPreset, UpscaleImageWithModelIfNeed, MaskFromFaceModel etc."
version = "1.1.1"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/zhangp365/ComfyUI-utils-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "zhangp365"
DisplayName = "ComfyUI-utils-nodes"
Icon = ""
